# Base
seed: 9999

# FHIR server url
fhir_url: http://localhost:8080/fhir    # Optional: set your FHIR server URL here

# Data configs
project: ./synthetic_data/
data_name: hospital_small    # Output path: ./synthetic_data/hospital_small/data
hospital_data:
    hospital_n: 10           # Number of hospitals to synthesize
    start_date:
        min: 2025-03-17      # ISO format: YYYY-MM-DD
        max: 2025-09-21      
    days: 7                  # Simulation period (in days)
    interval_hour: 0.25      # Time unit expressed in hours
    start_hour:              # Possible hospital opening hours
        min: 9
        max: 10
    end_hour:                # Possible hospital closing hours
        min: 18
        max: 19
    department_per_hospital:
        min: 7
        max: 9
    doctor_per_department:
        min: 1
        max: 1
    working_days:                   # Number of days each doctor works during the simulation period
        min: 3
        max: 4
    doctor_capacity_per_hour:
        min: 1
        max: 4
    doctor_has_schedule_prob: 0     # Probability that a doctor has at least one fixed schedule
    schedule_coverage_ratio:        # Proportion of fixed schedules relative to total working hours
        min: 0.4
        max: 0.6
    appointment_coverage_ratio:   # Proportion of appointments scheduled outside fixed schedules
        min: 0.2
        max: 0.5
    first_visit:
        preference:
            type: ['asap', 'doctor', 'date']    # Types of patient scheduling preferences
            probs: [0.4, 0.4, 0.2]              # Probability distribution for each preference type
        symptom:
            type: ['simple', 'with_history']    # 'simple' = no referral; 'with_history' = referral case
            probs: [0.7, 0.3]                   # Probability distribution for symptom types
    follow_up_visit:
        n_machines_per_test:
            min: 1
            max: 3
        test_per_department:
            min: 1
            max: 6
        test_has_schedule_prob: 0.2             # Probability that a test has at least one fixed schedule
        test_fixed_schedule_ratio:              # Proportion of a test's fixed schedules relative to total working hours
            min: 0.02
            max: 0.05
        test_day_closed_prob: 0.4
        test_per_patient:
            min: 1
            max: 4
        test_schedule_appointment_ratio:            # Proportion of a test's appontment schedules relative to vacant slots
            min: 0.2
            max: 0.4
        cross_department_test_prob: 0.2             # Probability of tests from other departments
        include_consultation: True                 # Whether to include post-test doctor consultation
        preference:
            type: ['throughput_max', 'visit_min', 'stay_min']    # Types of patient preferences.